# Source: servicemesh-jaeger-resource/templates/create-cassandra-user-cm.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: create-cassandra-user-cm
  namespace: tks-msa
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "10"
data:
  create_user.sh: |-
    #!/bin/sh
    set -ex
    kubectl exec -it -n tks-msa cassandra-dc-tks-sts-0 -c cassandra \
      -- cqlsh -u $CASS_USERNAME -p $CASS_PASSWORD \
           -e "CREATE ROLE IF NOT EXISTS tks WITH SUPERUSER = true AND LOGIN = true AND PASSWORD = 'tksword';"
