# Source: istio-gateway/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: istio-ingressgateway
  namespace: tks-gateway
  labels:
    helm.sh/chart: istio-gateway-1.17.2
    app: "istio-ingressgateway"
    istio: ingressgateway
    app.kubernetes.io/version: "1.17.2"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: istio-ingressgateway
  annotations:
    {}
spec:
  type: NodePort
  ports:
    - name: status-port
      nodePort: 30013
      port: 15021
      protocol: TCP
      targetPort: 15021
    - name: http2
      nodePort: 30014
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      nodePort: 30015
      port: 443
      protocol: TCP
      targetPort: 443
  selector:
    app: "istio-ingressgateway"
    istio: ingressgateway
