# Source: cluster-api-byoh/templates/kubeadm-control-plane.yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: ByoMachineTemplate
metadata:
  name: cluster.local-control-plane
  namespace: byoh-reference
spec:
  template:
    spec:
      selector:
        matchLabels:
          role: cluster.local-control-plane
      installerRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: K8sInstallerConfigTemplate
        name: cluster.local-control-plane
        namespace: byoh-reference
