{
 "title": "[TKS] Container Log Dashboard",
 "description": "logging dashboard for container logs on TACO using https://grafana.com/grafana/dashboards/12611-logging-universal-dashboard/",
 "tags": [
  "Loki",
  "logging"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "cluster", "label": "Cluster", "query": "label_values(cluster)" },
   {
    "name": "kubernetes_namespace_name",
    "label": "Namespace",
    "query": "label_values({cluster=~\"$cluster\"}, kubernetes_namespace_name)"
   },
   {
    "name": "kubernetes_pod_name",
    "label": "Pod",
    "query": "label_values({cluster=~\"$cluster\", kubernetes_namespace_name=\"$kubernetes_namespace_name\"}, kubernetes_pod_name)"
   },
   {
    "name": "kubernetes_container_name",
    "label": "Container",
    "query": "label_values({cluster=~\"$cluster\", kubernetes_namespace_name=\"$kubernetes_namespace_name\",kubernetes_pod_name=\"$kubernetes_pod_name\"}, kubernetes_container_name)"
   },
   { "name": "searchable_pattern", "label": "Search (case insensitive)" }
  ]
 },
 "panels": [
  {
   "title": "Total  Count of logs",
   "type": "stat",
   "description": "Total  Count of log lines in the specified time range",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({cluster=~\"$cluster\", kubernetes_namespace_name=\"$kubernetes_namespace_name\", kubernetes_container_name=~\"$kubernetes_container_name\", kubernetes_pod_name=~\"$kubernetes_pod_name\"})[$__interval]))"
    }
   ]
  },
  {
   "title": "Total Count: of \"$searchable_pattern\"",
   "type": "stat",
   "description": "Total Count: of $searchable_pattern in the specified time range",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({cluster=~\"$cluster\", kubernetes_namespace_name=\"$kubernetes_namespace_name\", kubernetes_container_name=~\"$kubernetes_container_name\", kubernetes_pod_name=~\"$kubernetes_pod_name\"} |~ \"(?i)$searchable_pattern\")[$__interval]))"
    }
   ]
  },
  {
   "title": "Live logs",
   "type": "logs",
   "description": "Live logs is a like 'tail -f' in a real time",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "{cluster=~\"$cluster\", kubernetes_namespace_name=\"$kubernetes_namespace_name\", kubernetes_pod_name=~\"$kubernetes_pod_name\", kubernetes_container_name=~\"$kubernetes_container_name\"} |~ \"(?i)$searchable_pattern\" "
    }
   ]
  },
  {
   "title": "logs (/Container)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 12 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(count_over_time(({cluster=~\"$cluster\", kubernetes_namespace_name=\"$kubernetes_namespace_name\", kubernetes_pod_name=~\"$kubernetes_pod_name\"})[$__interval])) by (kubernetes_container_name)"
    }
   ]
  },
  {
   "title": "Matched word: \"$searchable_pattern\" (/Pod)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 12, "x": 7, "y": 12 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(count_over_time(({cluster=~\"$cluster\", kubernetes_namespace_name=\"$kubernetes_namespace_name\", kubernetes_pod_name=~\"$kubernetes_pod_name\", kubernetes_container_name=~\"$kubernetes_container_name\"} |~ \"(?i)$searchable_pattern\")[$__interval])) by (kubernetes_pod_name)"
    }
   ]
  },
  {
   "title": "\"$searchable_pattern\" Percentage for specified time",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({cluster=~\"$cluster\", kubernetes_namespace_name=\"$kubernetes_namespace_name\", kubernetes_container_name=~\"$kubernetes_container_name\", kubernetes_pod_name=~\"$kubernetes_pod_name\"} |~ \"(?i)$searchable_pattern\")[$__interval])) * 100 / sum(count_over_time(({cluster=~\"$cluster\", kubernetes_namespace_name=\"$kubernetes_namespace_name\", kubernetes_container_name=~\"$kubernetes_container_name\", kubernetes_pod_name=~\"$kubernetes_pod_name\"})[$__interval]))"
    }
   ]
  },
  {
   "title": "\"$searchable_pattern\" COUNT (/Pod)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time(({cluster=~\"$cluster\", kubernetes_namespace_name=\"$kubernetes_namespace_name\", kubernetes_pod_name=~\"$kubernetes_pod_name\", kubernetes_container_name=~\"$kubernetes_container_name\"} |~ \"(?i)$searchable_pattern\")[$__interval])) by (kubernetes_pod_name)"
    }
   ]
  },
  {
   "title": "\"$searchable_pattern\" Rate (/Pod)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(({cluster=~\"$cluster\", kubernetes_namespace_name=\"$kubernetes_namespace_name\", kubernetes_container_name=~\"$kubernetes_container_name\", kubernetes_pod_name=~\"$kubernetes_pod_name\"} |~ \"(?i)$searchable_pattern\")[30s])) by (kubernetes_pod_name)"
    }
   ]
  },
  {
   "title": "Count of logs historical",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time(({cluster=~\"$cluster\", kubernetes_namespace_name=\"$kubernetes_namespace_name\", kubernetes_pod_name=~\"$kubernetes_pod_name\"})[$__interval])) by (kubernetes_container_name)"
    }
   ]
  }
 ]
}