# Source: servicemesh-jaeger-resource/templates/create-cassandra-user-cm.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader
  namespace: tks-msa
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "10"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-reader
subjects:
- kind: ServiceAccount
  name: default
  namespace: tks-msa
