# Source: minio/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: minio
  namespace: "lma"
  labels:
    app: minio
    chart: minio-5.0.4
    release: minio
    heritage: Helm
type: Opaque
data:
  rootUser: "VVlmdE9kTEczTkE5dWZKRHJZRk4="
  rootPassword: "Ym9pUlFmb0lZOHVycVhaVDljNWlyZUZkVXpZTnlyN3IwSDVUaHZjZQ=="
