# Source: minio/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: minio
  namespace: "lma"
  labels:
    app: minio
    chart: minio-5.0.4
    release: minio
    heritage: Helm
type: Opaque
data:
  rootUser: "YWdZOHcxNk5sWjhKV0NBUG9DSzA="
  rootPassword: "akwyRG8wckFsYnFqYzVDYTAwcU5CSDkxTFdFd0taUG4wZW5nUWRsdg=="
