# Source: minio/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: "lma"
  labels:
    app: minio
    chart: minio-5.0.4
    release: minio
    heritage: Helm
    monitoring: "true"
spec:
  type: LoadBalancer
  loadBalancerIP: 
  ports:
    - name: http
      port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: minio
    release: minio
