# Source: k8ssandra-operator/charts/cass-operator/templates/rolebinding.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8ssandra-operator-cass-operator
  labels:     
    app.kubernetes.io/name: cass-operator
    helm.sh/chart: cass-operator-0.40.0
    app.kubernetes.io/instance: k8ssandra-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: k8ssandra-k8ssandra-operator-tks-msa
subjects:
  - kind: ServiceAccount
    name: k8ssandra-operator-cass-operator
roleRef:
  kind: Role
  name: k8ssandra-operator-cass-operator
  apiGroup: rbac.authorization.k8s.io
