# Source: thanos/templates/ruler/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: thanos-ruler
  namespace: "lma"
  labels:
    app.kubernetes.io/name: thanos
    helm.sh/chart: thanos-12.3.2-skt
    app.kubernetes.io/instance: thanos
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: ruler
  annotations:
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: http
      protocol: TCP
      name: http
      nodePort: null
    - port: 10901
      targetPort: grpc
      protocol: TCP
      name: grpc
      nodePort: null
  selector:
    app.kubernetes.io/name: thanos
    app.kubernetes.io/instance: thanos
    app.kubernetes.io/component: ruler
