# Source: harbor/templates/registry/registry-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: "harbor-registry-htpasswd"
  labels:
    heritage: Helm
    release: harbor
    chart: harbor
    app: "harbor"
type: Opaque
data:
  REGISTRY_HTPASSWD: "aGFyYm9yX3JlZ2lzdHJ5X3VzZXI6JDJhJDEwJEZDdjJJTW5BNWdUVm5kSXo4ZHJDS2VRbE5QVFdCSXpyM1RFdEpVSUZHLm16S2ZlcE10cDBH"
