# Source: istiod/templates/reader-clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: istio-reader-clusterrole-tks-msa
  labels:
    app: istio-reader
    release: istiod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: istio-reader-clusterrole-tks-msa
subjects:
  - kind: ServiceAccount
    name: istio-reader-service-account
    namespace: tks-msa
