# Source: istiod/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: istio
  namespace: tks-msa
  labels:
    istio.io/rev: default
    install.operator.istio.io/owning-resource: unknown
    operator.istio.io/component: "Pilot"
    release: istiod
data:

  # Configuration file for the mesh networks to be used by the Split Horizon EDS.
  meshNetworks: |-
    networks: {}

  mesh: |-
    defaultConfig:
      discoveryAddress: istiod.tks-msa.svc:15012
      tracing:
        zipkin:
          address: jaeger-operator-jaeger-collector.tks-msa:9411
    enablePrometheusMerge: true
    rootNamespace: tks-msa
    trustDomain: cluster.local
