---
# Source: prepare-decapod-controller/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: argo-postgres-config
  namespace: argo
type: Opaque
data:
  postgres-password:  "JHtEQVRBQkFTRV9QQVNTV09SRH0="
  postgres-username:  "JHtEQVRBQkFTRV9VU0VSfQ=="

