# Source: thanos/templates/query/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: thanos-query
  namespace: "lma"
  labels:
    app.kubernetes.io/name: thanos
    helm.sh/chart: thanos-12.3.2-skt
    app.kubernetes.io/instance: thanos
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: query
  annotations:
automountServiceAccountToken: true
