---
# Source: gatekeeper/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gatekeeper
  labels:
    helm.sh/chart: gatekeeper-0.1.39
    app.kubernetes.io/name: gatekeeper
    app.kubernetes.io/instance: gatekeeper
    app.kubernetes.io/version: "2.8.0"
    app.kubernetes.io/managed-by: Helm
