---
# Source: opa-scorecard/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: opa-exporter-opa-scorecard
  labels:
    helm.sh/chart: opa-scorecard-0.1.0
    app.kubernetes.io/name: opa-scorecard
    app.kubernetes.io/instance: opa-exporter
    app.kubernetes.io/version: "v0.0.4"
    app.kubernetes.io/managed-by: Helm
