# Source: thanos/templates/ruler/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: thanos-ruler-configmap
  namespace: "lma"
  labels:
    app.kubernetes.io/name: thanos
    helm.sh/chart: thanos-12.3.2-skt
    app.kubernetes.io/instance: thanos
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: ruler
data:
  ruler.yml: |-
    groups:
    - name: tks
      rules:
      - alert: PrometheusDown
        expr: absent(up{prometheus="lma/lma-prometheus"})
      - alert: node-cpu-high-load
        annotations:
          Checkpoint: 일시적인 Service Traffic의 증가가 관측되지 않았다면, Alert발생 노드에서 실행 되는 pod중 CPU
            자원을 많이 점유하는 pod의 설정을 점검해 보시길 제안드립니다. 예를 들어 pod spec의 limit 설정으로 과도한 CPU자원
            점유을 막을 수 있습니다.
          description: 워커 노드 CPU가 과부하 상태입니다. 일시적인 서비스 Traffic 증가, Workload의 SW 오류, Server
            HW Fan Fail등 다양한 원인으로 인해 발생할 수 있습니다.
          discriminative: $labels.taco_cluster, $labels.instance
          message: 클러스터({{ $labels.taco_cluster }})의 노드({{ $labels.instance }})의 idle
            process의 cpu 점유율이 3분 동안 0% 입니다. (현재 사용률 {{$value}})
          summary: Cpu resources of the node {{ $labels.instance }} are running low.
        expr: (avg by (taco_cluster, instance) (rate(node_cpu_seconds_total{mode="idle"}[60s])))
          < 0
        for: 3m
        labels:
          severity: warning
      - alert: node-memory-high-utilization
        annotations:
          Checkpoint: 일시적인 Service Traffic의 증가가 관측되지 않았다면, Alert발생 노드에서 실행되는 pod중 Memory
            사용량이 높은 pod들에 대한 점검을 제안드립니다.
          descriptioon: 워커 노드의 Memory 사용량이 80%를 넘었습니다. 일시적인 서비스 증가 및 SW 오류등 다양한 원인으로 발생할
            수 있습니다.
          discriminative: $labels.taco_cluster, $labels.instance
          message: 클러스터({{ $labels.taco_cluster }})의 노드({{ $labels.instance }})의 Memory
            사용량이 3분동안 80% 를 넘어서고 있습니다. (현재 사용률 {{$value}})
          summary: Memory resources of the node {{ $labels.instance }} are running low.
        expr: (node_memory_MemAvailable_bytes/node_memory_MemTotal_bytes) <  0.2
        for: 3m
        labels:
          severity: warning
      - alert: node-disk-full
        annotations:
          Checkpoint: Disk 용량 최적화(삭제 및 Backup)을 수행하시길 권고합니다. 삭제할 내역이 없으면 증설 계획을 수립해 주십시요.
          description: 현재 Disk 사용 추세기준 24시간 내에 Disk 용량이 꽉 찰 것으로 예상됩니다.
          discriminative: $labels.taco_cluster, $labels.instance
          message: 지난 6시간동안의 추세로 봤을 때, 클러스터({{ $labels.taco_cluster }})의 노드({{ $labels.instance
            }})의 root 볼륨은 24시간 안에 Disk full이 예상됨
          summary: Memory resources of the node {{ $labels.instance }} are running low.
        expr: predict_linear(node_filesystem_free_bytes{mountpoint="/"}[6h], 24*3600)
          < 0
        for: 30m
        labels:
          severity: critical
      - alert: pvc-full
        annotations:
          Checkpoint: Disk 용량 최적화(삭제 및 Backup)을 수행하시길 권고합니다. 삭제할 내역이 없으면 증설 계획을 수립해 주십시요.
          description: 현재 Disk 사용 추세기준 24시간 내에 Disk 용량이 꽉 찰것으로 예상됩니다. ({{ $labels.taco_cluster
            }} 클러스터, {{ $labels.persistentvolumeclaim }} PVC)
          discriminative: $labels.taco_cluster, $labels.persistentvolumeclaim
          message: 지난 6시간동안의 추세로 봤을 때, 클러스터({{ $labels.taco_cluster }})의 파드({{ $labels.persistentvolumeclaim
            }})가 24시간 안에 Disk full이 예상됨
          summary: Disk resources of the volume(pvc) {{ $labels.persistentvolumeclaim
            }} are running low.
        expr: predict_linear(kubelet_volume_stats_available_bytes[6h], 24*3600) < 0
        for: 30m
        labels:
          severity: critical
      - alert: pod-restart-frequently
        annotations:
          Checkpoint: pod spec. 에 대한 점검이 필요합니다. pod의 log 및 status를 확인해 주세요.
          description: 특정 Pod가 빈번하게 재기동 되고 있습니다. 점검이 필요합니다. ({{ $labels.taco_cluster }}
            클러스터, {{ $labels.pod }} 파드)
          discriminative: $labels.taco_cluster, $labels.pod, $labels.namespace
          message: 클러스터({{ $labels.taco_cluster }})의 파드({{ $labels.pod }})가 30분 동안 5회
            이상 재기동 ({{ $value }}회)
        expr: increase(kube_pod_container_status_restarts_total{namespace!="kube-system"}[60m:])
          > 2
        for: 30m
        labels:
          severity: critical
