# Source: k8ssandra-operator/charts/cass-operator/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8ssandra-operator-cass-operator
  labels:     
    app.kubernetes.io/name: cass-operator
    helm.sh/chart: cass-operator-0.40.0
    app.kubernetes.io/instance: k8ssandra-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: k8ssandra-k8ssandra-operator-tks-msa
    control-plane: k8ssandra-operator-cass-operator-controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cass-operator
      app.kubernetes.io/instance: k8ssandra-operator
      app.kubernetes.io/part-of: k8ssandra-k8ssandra-operator-tks-msa
  template:
    metadata:
      labels:        
        app.kubernetes.io/name: cass-operator
        helm.sh/chart: cass-operator-0.40.0
        app.kubernetes.io/instance: k8ssandra-operator
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/part-of: k8ssandra-k8ssandra-operator-tks-msa
        control-plane: k8ssandra-operator-cass-operator-controller-manager
    spec:
      serviceAccountName: k8ssandra-operator-cass-operator
      securityContext:
        {}
      containers:
        - name: cass-operator
          args:
          - --config=/configs/controller_manager_config.yaml
          command:
          - /manager
          securityContext:
            readOnlyRootFilesystem: true
            runAsGroup: 65534
            runAsNonRoot: true
            runAsUser: 65534
          image: harbor.taco-cat.xyz/tks/cass-operator:v1.14.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9443
              name: webhook-server
              protocol: TCP
          volumeMounts:
            - mountPath: /tmp/k8s-webhook-server/serving-certs
              name: cass-operator-certs-volume
              readOnly: true
            - mountPath: /configs
              name: manager-config
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {}
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      nodeSelector:
        tks-msa: enabled
      volumes:
        - name: cass-operator-certs-volume
          secret:
            defaultMode: 420
            secretName: k8ssandra-operator-cass-operator-webhook-server-cert
        - configMap:
            name: k8ssandra-operator-cass-operator-manager-config
          name: manager-config
