# Source: k8ssandra-operator/templates/crd/batch_job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: k8ssandra-operator-crd-upgrader-job-k8ssandra
  labels:     
    app.kubernetes.io/name: k8ssandra-operator
    helm.sh/chart: k8ssandra-operator-1.6.0
    app.kubernetes.io/instance: k8ssandra-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: k8ssandra-k8ssandra-operator-tks-msa
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "10"
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:         
        app.kubernetes.io/name: k8ssandra-operator
        helm.sh/chart: k8ssandra-operator-1.6.0
        app.kubernetes.io/instance: k8ssandra-operator
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/part-of: k8ssandra-k8ssandra-operator-tks-msa
    spec:
      restartPolicy: OnFailure
      serviceAccountName: k8ssandra-operator-crd-upgrader-k8ssandra
      containers:
        - name: crd-upgrade-job-k8ssandra
          image: harbor.taco-cat.xyz/tks/k8ssandra-tools:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          args:
            - -upgradecrds
            - --targetVersion
            - 1.6.0
            - --chartName
            - k8ssandra-operator

