---
# Source: servicemesh-kiali-resource/templates/kiali-controlplane.yaml
apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  namespace: tks-msa
  annotations:
    ansible.operator-sdk/verbosity: "1"
spec:
  istio_namespace: tks-msa
  deployment:
    accessible_namespaces: ["**"]
    ingress_enabled: false
    namespace: tks-msa
    image_name: harbor.taco-cat.xyz/tks/kiali
    image_version: v1.63.0
    replicas: 1
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1024Mi
    node_selector:
      tks-msa: enabled
    service_type: NodePort
    additional_service_yaml:
      nodePort: 30010
  auth:
    strategy: openid
    openid:
      client_id: client-prefix-kiali
      issuer_uri: https://keycloak.com/auth/realms/oraganization
      username_claim: preferred_username
      scopes: 
      - openid
      - email
      disable_rbac: true
  external_services:
    custom_dashboards:
      enabled: true
    istio:
      config_map_name: istio
      istio_identity_domain: svc.cluster.local
      component_status:
        enabled: true
        components:
        - app_label: istiod
          is_core: true
          is_proxy: false
        - app_label: istio-ingressgateway
          is_core: true
          is_proxy: true
          namespace: tks-gateway
        - app_label: istio-egressgateway
          is_core: false
          is_proxy: true
          namespace: tks-gateway
    prometheus:
      url: http://lma-prometheus.lma.svc:9090
    tracing:
      enabled: true
      namespace_selector: true
      in_cluster_url: http://jaeger-operator-jaeger-query.tks-msa:16686
      url: https://jaeger-v2.taco-cat.xyz
      use_grpc: false
    grafana:
      auth:
        password: password
        type: basic
        use_kiali_token: false
        username: admin
      enabled: true
      in_cluster_url: http://grafana.lma.svc:80
      url: https://grafana-v2.taco-cat.xyz
  server:
    metrics_enabled: true
    metrics_port: 9090
    port: 20001
    web_root: /
  istio_labels:
    app_label_name: "app"
    injection_label_name: "istio-injection"
    injection_label_rev:  "istio.io/rev"
    version_label_name: "version"

