---
# Source: servicemesh-jaeger-resource/templates/jaeger-controlplane.yaml
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger-operator-jaeger
  namespace: tks-msa
spec:
  strategy: production
  sampling:
    options:
      default_strategy:
        type: probabilistic
        param: 10
  ingress:
    enabled: false
  collector:
    image: harbor.taco-cat.xyz/tks/jaeger-collector:1.35.0
    maxReplicas: 5
    resources:
      requests:
        cpu: 500m
        memory: 1024Mi
      limits:
        cpu: 1000m
        memory: 2048Mi
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: tks-msa
              operator: In
              values:
              - enabled
  storage:
    type: cassandra
    options:
      cassandra:
        servers: cassandra-dc-service.tks-msa.svc
        username: tks
        password: tksword
        keyspace: jaeger_v1_datacenter
    cassandraCreateSchema:
      image: harbor.taco-cat.xyz/tks/jaeger-cassandra-schema:1.35.0
      datacenter: dc
      datacenter: dc
      mode: prod
      timeout: 3m
    dependencies:
      enabled: true
      image: harbor.taco-cat.xyz/tks/spark-dependencies:1.35.0
  query:
    image: harbor.taco-cat.xyz/tks/jaeger-query:1.35.0
    options:
      query.base-path: /
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: tks-msa
              operator: In
              values:
              - enabled
  agent:
    image: harbor.taco-cat.xyz/tks/jaeger-agent:1.35.0
