# Source: cluster-api-aws/templates/machine-pool.yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSManagedMachinePool
metadata:
  name: cluster.local-mp-taco
  namespace: eks-reference
spec:
  eksNodegroupName: cluster.local-mp-taco
  instanceType: t3.2xlarge
  diskSize: 200
  scaling:
    maxSize: 16
    minSize: 1
  remoteAccess:
    sshKeyName: CHANGEME
