# Source: cluster-api-aws/templates/aws-managed-control-plane.yaml
apiVersion: controlplane.cluster.x-k8s.io/v1beta2
kind: AWSManagedControlPlane
metadata:
  name: cluster.local
  namespace: eks-reference
spec:
  eksClusterName: cluster.local
  region: CHANGEME
  sshKeyName: CHANGEME
  version: v1.29.8
  addons:
    - conflictResolution: overwrite
      name: aws-ebs-csi-driver
      version: v1.34.0-eksbuild.1
    - conflictResolution: overwrite
      name: vpc-cni
      version: v1.18.3-eksbuild.2
  identityRef:
    kind: AWSClusterRoleIdentity
    name: CHANGEME-account-role
  bastion:
    enabled: false
