# Source: cluster-api-aws/templates/machine-pool.yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: cluster.local-mp-taco
  namespace: eks-reference
spec:
  clusterName: cluster.local
  replicas: 3
  template:
    metadata:
      labels:
            servicemesh: enabled
            taco-ingress-gateway: enabled
            taco-lma: enabled
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: cluster.local
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
        kind: AWSManagedMachinePool
        name: cluster.local-mp-taco
        namespace: eks-reference
      version: v1.22.5

