{
 "title": "[TKS] Syslog Dashboard",
 "description": "logging dashboard for container logs on TACO",
 "tags": [
  "Loki",
  "logging"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "cluster", "label": "Cluster", "query": "label_values(cluster)" },
   {
    "name": "host",
    "label": "NodeName",
    "query": "label_values({cluster=~\"$cluster\", host=~\".+\"}, host)"
   },
   {
    "name": "ident",
    "label": "Identifier",
    "query": "label_values({cluster=~\"$cluster\", host=\"$host\"}, ident)"
   },
   { "name": "searchable_pattern", "label": "Search (case insensitive)" }
  ]
 },
 "panels": [
  {
   "title": "Total  Count of logs",
   "type": "stat",
   "description": "Total  Count of log lines in the specified time range",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({host=\"$host\",  ident=~\"$ident\"})[$__interval]))"
    }
   ]
  },
  {
   "title": "Total Count: of \"$searchable_pattern\"",
   "type": "stat",
   "description": "Total Count: of $searchable_pattern in the specified time range",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({host=\"$host\",  ident=~\"$ident\"} |~ \"(?i)$searchable_pattern\")[$__interval]))"
    }
   ]
  },
  {
   "title": "Live logs",
   "type": "logs",
   "description": "Live logs is a like 'tail -f' in a real time",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "{host=\"$host\", ident=~\"$ident\"} |~ \"(?i)$searchable_pattern\" "
    }
   ]
  },
  {
   "title": "logs (/Identifier)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 12 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(count_over_time(({host=\"$host\"})[$__interval])) by (ident)"
    }
   ]
  },
  {
   "title": "Matched word: \"$searchable_pattern\" (/Identifier)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 12, "x": 7, "y": 12 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(count_over_time(({host=\"$host\", ident=~\"$ident\"} |~ \"(?i)$searchable_pattern\")[$__interval])) by (ident)"
    }
   ]
  },
  {
   "title": "\"$searchable_pattern\" Percentage for specified time",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({host=\"$host\",  ident=~\"$ident\"} |~ \"(?i)$searchable_pattern\")[$__interval])) * 100 / sum(count_over_time(({host=\"$host\",  ident=~\"$ident\"})[$__interval]))"
    }
   ]
  },
  {
   "title": "\"$searchable_pattern\" COUNT (/Identifier)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time(({host=\"$host\", ident=~\"$ident\"} |~ \"(?i)$searchable_pattern\")[$__interval])) by (ident)"
    }
   ]
  },
  {
   "title": "\"$searchable_pattern\" Rate (/Identifier)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(({host=\"$host\",  ident=~\"$ident\"} |~ \"(?i)$searchable_pattern\")[30s])) by (ident)"
    }
   ]
  },
  {
   "title": "Count of logs historical",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time(({host=\"$host\", ident=~\"$ident\"})[$__interval])) by (ident)"
    }
   ]
  }
 ]
}