# Source: k8ssandra-operator/charts/cass-operator/templates/configmap.yaml
kind: ConfigMap
metadata:
  name: k8ssandra-operator-cass-operator-manager-config
  labels:     
    app.kubernetes.io/name: cass-operator
    helm.sh/chart: cass-operator-0.40.0
    app.kubernetes.io/instance: k8ssandra-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: k8ssandra-k8ssandra-operator-tks-msa
apiVersion: v1
data:
  controller_manager_config.yaml: |
    apiVersion: config.k8ssandra.io/v1beta1
    kind: OperatorConfig
    health:
      healthProbeBindAddress: :8081
    metrics:
      bindAddress: 127.0.0.1:8080
    webhook:
      port: 9443
    leaderElection:
      leaderElect: true
      resourceName: b569adb7.cassandra.datastax.com
    disableWebhooks: false
    imageConfigFile: /configs/image_config.yaml
  image_config.yaml: |
    apiVersion: config.k8ssandra.io/v1beta1
    kind: ImageConfig
    images:
      system-logger: "k8ssandra/system-logger:v1.14.0"
      config-builder: "datastax/cass-config-builder:1.0-ubi7"
    imagePullPolicy: IfNotPresent
    defaults:
      # Note, postfix is ignored if repository is not set
      cassandra:
        repository: "k8ssandra/cass-management-api"
      dse:
        repository: "datastax/dse-server"
        suffix: "-ubi7"
