---
# Source: postgresql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: postgresql
  namespace: "decapod-db"
  labels:
    app.kubernetes.io/name: postgresql
    helm.sh/chart: postgresql-12.1.2
    app.kubernetes.io/instance: postgresql
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  postgres-password: "TU9LV2paUHk0Sg=="
  # We don't auto-generate LDAP password when it's not provided as we do for other passwords
