# Source: thanos/templates/ruler/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: thanos-ruler-configmap
  namespace: "lma"
  labels:
    app.kubernetes.io/name: thanos
    helm.sh/chart: thanos-12.3.2-skt
    app.kubernetes.io/instance: thanos
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: ruler
data:
  ruler.yml: |-
    groups:
    - name: metamonitoring
      rules:
      - alert: PrometheusDown
        expr: absent(up{prometheus="monitoring/prometheus-operator"})
