# Source: keycloak-operator/templates/deploy-keycloak-operator.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: keycloak-operator
  template:
    metadata:
      labels:
        name: keycloak-operator
    spec:
      serviceAccountName: keycloak-operator
      containers:
        - name: keycloak-operator
          image: "quay.io/keycloak/keycloak-operator:17.0.0"
          imagePullPolicy: IfNotPresent
          command:
          - keycloak-operator
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "keycloak-operator"
            - name: RELATED_IMAGE_KEYCLOAK
              value: "quay.io/keycloak/keycloak:17.0.0-legacy"
            - name: RELATED_IMAGE_KEYCLOAK_INIT_CONTAINER
              value: "quay.io/keycloak/keycloak-init-container:17.0.0-legacy"
          resources:
            {}

