# Source: gatekeeper/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatekeeper
  labels:
    helm.sh/chart: gatekeeper-0.1.39
    app.kubernetes.io/name: gatekeeper
    app.kubernetes.io/instance: gatekeeper
    app.kubernetes.io/version: "2.8.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: gatekeeper
      app.kubernetes.io/instance: gatekeeper
  template:
    metadata:
      annotations:
        checksum/config: "5d30be1a8bbf5ff3262853e3043b1c99f55984d06ea825194863f8622ac6390c"
      labels:
        app.kubernetes.io/name: gatekeeper
        app.kubernetes.io/instance: gatekeeper
    spec:
      automountServiceAccountToken: false
      serviceAccountName: gatekeeper
      containers:
        - name: gatekeeper
          securityContext:
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          image: "harbor.taco-cat.xyz/tks/gatekeeper:2.8.0"
          imagePullPolicy: IfNotPresent
          args:
            - --config
            - /etc/gatekeeper/config.yaml
          ports:
            - name: proxy
              containerPort: 3000
              protocol: TCP
            - name: admin
              containerPort: 4000
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /oauth/health
              port: admin
          resources:
            limits: {}
            requests: {}
          volumeMounts:
            - mountPath: /etc/gatekeeper
              name: config
      volumes:
        - secret:
            secretName: gatekeeper
          name: config
      nodeSelector:
        tks-msa: enabled

