# Source: gatekeeper/templates/config.yaml
apiVersion: v1
kind: Secret
metadata:
  name: gatekeeper
  labels:
    helm.sh/chart: gatekeeper-0.1.39
    app.kubernetes.io/name: gatekeeper
    app.kubernetes.io/instance: gatekeeper
    app.kubernetes.io/version: "2.8.0"
    app.kubernetes.io/managed-by: Helm
type: Opaque
stringData:
  config.yaml: |
    client-id: client-prefix-gatekeeper-jaeger
    client-secret: gatekeeper-secret
    discovery-url: https://keycloak.com/auth/realms/oraganization
    enable-metrics: false
    listen: 0.0.0.0:3000
    listen-admin: 0.0.0.0:4000
    upstream-url: http://jaeger-operator-jaeger-query.tks-msa.svc
