# Source: istio-ingress-gateway/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: istio-egress-gateway
  namespace: istio-ingress
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: istio-egress-gateway
subjects:
- kind: ServiceAccount
  name: istio-egress-gateway
