# Source: istio-ingress-gateway/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: istio-egress-gateway
  namespace: istio-ingress
  labels:
    helm.sh/chart: istio-ingress-gateway-1.13.1
    app: "istio-egress-gateway"
    istio: egress-gateway
    app.kubernetes.io/version: "1.13.1"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: istio-egress-gateway
  annotations:
    {}
spec:
  type: ClusterIP
  ports:
    - name: status-port
      port: 15021
      protocol: TCP
      targetPort: 15021
    - name: http2
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
  selector:
    app: "istio-egress-gateway"
    istio: egress-gateway
