# Source: minio/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: minio
  namespace: "lma"
  labels:
    app: minio
    chart: minio-5.0.4
    release: minio
    heritage: Helm
type: Opaque
data:
  rootUser: "ZzBmYXQ5Z1dFSG51VU9JRlA4QUc="
  rootPassword: "TVlTbEJVOWl3dWhIRlF6aVU1b3dEMHBhUWJMMGlvOHNVbVBtcnRPVw=="
