# Source: cluster-api-aws/templates/machine-pool.yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSMachinePool
metadata:
  name: cluster.local-mp-taco
  namespace: aws-reference
spec:
  awsLaunchTemplate:
    instanceType: t3.2xlarge
    sshKeyName: CHANGEME
    iamInstanceProfile: "nodes.cluster-api-provider-aws.sigs.k8s.io"
    rootVolume:
      size: 200
      type: gp2
  maxSize: 16
  minSize: 1
  subnets:
  - filters:
    - name: "tag:sigs.k8s.io/cluster-api-provider-aws/role"
      values:
      - "private"
    - name: "tag:Name"
      values:
      - "*cluster.local*"
