# Source: tks-apis/templates/tks-api/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tks-api
  namespace: tks
  labels:
    helm.sh/chart: tks-apis-0.1.2
    app.kubernetes.io/service: tks
    app.kubernetes.io/name: tks-api
    app.kubernetes.io/version: "0.1.2"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/service: tks
      app.kubernetes.io/name: tks-api
  template:
    metadata:
      labels:
        app.kubernetes.io/service: tks
        app.kubernetes.io/name: tks-api
    spec:
      serviceAccountName: tks-api
      securityContext:
        null
      containers:
        - name: tks-apis
          securityContext:
            null
          image: "harbor.taco-cat.xyz/tks/tks-api:v3.0.1"
          imagePullPolicy: Always
          ports:
            - name: tks-api
              containerPort: 9110
              protocol: TCP
          command:
            - /app/backend/bin/server
          args: [
            "-port", "9110",
            "-revision", "main",
            "-git-account", "decapod10",
            "-dbname", "tks",
            "-dbhost", "${DATABASE_HOST}",
            "-dbport", "5432",
            "-dbuser", "tksuser",
            "-dbpassword", "${COMMON_PASSWORD}",
            "-argo-address", "http://argo-workflows-operator-server.argo.svc",
            "-argo-port", "2746",
            "-external-gitea-url", "http://localhost:30303",

            "-image-registry-url", "harbor.taco-cat.xyz/appserving",
            "-harbor-pw-secret", "harbor-core",
            "-git-repository-url", "github.com/openinfradev",

            "-keycloak-address", "http://keycloak.keycloak.svc:80/auth",
            "-keycloak-admin", "admin",
            "-keycloak-password", "admin",
            "-keycloak-client-secret", "secret",

            "-mail-provider", "aws",
            "-smtp-host", "localhost",
            "-smtp-port", "0",
            "-smtp-username", "admin",
            "-smtp-password", "admin",
            "-smtp-from-email", "admin",

            "-aws-region", "ap-northeast-2",
            "-aws-access-key-id", "AWS_SECRET_KEY",
            "-aws-secret-access-key", "AWS_SECRET_ACCESS_KEY"
          ]
          resources:
            null
