# Source: k8ssandra-operator/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8ssandra-operator
  labels:     
    app.kubernetes.io/name: k8ssandra-operator
    helm.sh/chart: k8ssandra-operator-1.6.0
    app.kubernetes.io/instance: k8ssandra-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: k8ssandra-k8ssandra-operator-tks-msa
    control-plane: k8ssandra-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: k8ssandra-operator
      app.kubernetes.io/instance: k8ssandra-operator
      app.kubernetes.io/part-of: k8ssandra-k8ssandra-operator-tks-msa
      control-plane: k8ssandra-operator
  template:
    metadata:
      labels:        
        app.kubernetes.io/name: k8ssandra-operator
        helm.sh/chart: k8ssandra-operator-1.6.0
        app.kubernetes.io/instance: k8ssandra-operator
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/part-of: k8ssandra-k8ssandra-operator-tks-msa
        control-plane: k8ssandra-operator
    spec:
      serviceAccountName: k8ssandra-operator
      securityContext:
        {}
      containers:
      - command:
        - /manager
        # args:
        # - --config=controller_manager_config.yaml
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: K8SSANDRA_CONTROL_PLANE
          value: "true"
        image: harbor.taco-cat.xyz/tks/k8ssandra-operator:v1.6.0
        imagePullPolicy: IfNotPresent
        securityContext:
            runAsGroup: 65534
            runAsNonRoot: true
            runAsUser: 65534
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: k8ssandra-operator
        ports:
          - containerPort: 9443
            name: webhook-server
            protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
            {}
        volumeMounts:
        - mountPath: /controller_manager_config.yaml
          name: manager-config
          subPath: controller_manager_config.yaml
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      terminationGracePeriodSeconds: 10
      nodeSelector:
        tks-msa: enabled
      volumes:
      - configMap:
          name: k8ssandra-operator-manager-config
        name: manager-config
      - name: cert
        secret:
          defaultMode: 420
          secretName: k8ssandra-operator-webhook-server-cert
