# Source: k8ssandra-operator/charts/cass-operator/templates/validatingwebhookconfiguration.yaml
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: k8ssandra-operator-cass-operator-selfsigned-issuer
  labels:     
    app.kubernetes.io/name: cass-operator
    helm.sh/chart: cass-operator-0.40.0
    app.kubernetes.io/instance: k8ssandra-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: k8ssandra-k8ssandra-operator-tks-msa
spec:
  selfSigned: {}
