---
# Source: istio-gateway/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-ingressgateway
  namespace: tks-gateway
  labels:
    helm.sh/chart: istio-gateway-1.17.2
    app: "istio-ingressgateway"
    istio: ingressgateway
    app.kubernetes.io/version: "1.17.2"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: istio-ingressgateway
