# Source: tks-apis/templates/tks-console/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: tks-console
  namespace: tks
  labels:
    helm.sh/chart: tks-apis-0.1.2
    app.kubernetes.io/service: tks
    app.kubernetes.io/name: tks-console
    app.kubernetes.io/version: "0.1.2"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP
  selector:
    app.kubernetes.io/service: tks
    app.kubernetes.io/name: tks-console
