# Source: tks-apis/templates/tks-batch/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tks-batch
  labels:
    helm.sh/chart: tks-apis-0.1.2
    app.kubernetes.io/service: tks
    app.kubernetes.io/name: tks-batch
    app.kubernetes.io/version: "0.1.2"
    app.kubernetes.io/managed-by: Helm
secrets:
- name: tks-batch-token
