# Source: tks-apis/templates/tks-console/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tks-console
  labels:
    helm.sh/chart: tks-apis-0.1.2
    app.kubernetes.io/service: tks
    app.kubernetes.io/name: tks-console
    app.kubernetes.io/version: "0.1.2"
    app.kubernetes.io/managed-by: Helm
