# Source: kube-prometheus-stack/templates/prometheus/prometheus.yaml
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: lma-prometheus
  namespace: lma
  labels:
    app: kube-prometheus-stack-prometheus
    
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/version: "48.3.1"
    app.kubernetes.io/part-of: kube-prometheus-stack
    chart: kube-prometheus-stack-48.3.1
    release: "prometheus"
    heritage: "Helm"
spec:
  alerting:
    alertmanagers:
      - namespace: lma
        name: lma-alertmanager
        port: http-web
        pathPrefix: "/"
        apiVersion: v2
  image: "harbor.taco-cat.xyz/tks/prometheus:v2.45.0"
  version: v2.45.0
  externalLabels:
    taco_cluster: cluster.local
  externalUrl: http://lma-prometheus.lma:9090
  nodeSelector:
    taco-lma: enabled
  paused: false
  replicas: 1
  shards: 1
  logLevel:  info
  logFormat:  logfmt
  listenLocal: false
  enableAdminAPI: false
  scrapeInterval: 30s
  scrapeTimeout: 10s
  evaluationInterval: 60s
  retention: "2d"
  tsdb:
    outOfOrderTimeWindow: 0s
  walCompression: true
  routePrefix: "/"
  serviceAccountName: lma-prometheus
  serviceMonitorSelector: {}
  serviceMonitorNamespaceSelector:
    matchLabels:
      name: lma

  podMonitorSelector: {}
  podMonitorNamespaceSelector:
    matchLabels:
      name: lma

  probeSelector:
    matchLabels:
      release: "prometheus"

  probeNamespaceSelector: {}
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
  ruleNamespaceSelector:
    matchLabels:
      name: lma

  ruleSelector: {}
  scrapeConfigSelector:
    matchLabels:
      release: "prometheus"

  scrapeConfigNamespaceSelector: {}
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
        storageClassName: taco-storage
  thanos:
    minTime: -3h
    objectStorageConfig:
      key: objstore.yml
      name: taco-objstore-secret
    version: v0.18.0
  portName: http-web
  hostNetwork: false
