# Source: prometheus-pushgateway/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    helm.sh/chart: prometheus-pushgateway-2.1.1
    app.kubernetes.io/name: prometheus-pushgateway
    app.kubernetes.io/instance: prometheus-pushgateway
    app.kubernetes.io/version: "v1.5.1"
    app.kubernetes.io/managed-by: Helm
  name: prometheus-pushgateway
  namespace: lma
spec:
  type: ClusterIP
  ports:
    - port: 9091
      targetPort: 9091
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: prometheus-pushgateway
    app.kubernetes.io/instance: prometheus-pushgateway
