---
# Source: prometheus-pushgateway/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    helm.sh/chart: prometheus-pushgateway-2.1.1
    app.kubernetes.io/name: prometheus-pushgateway
    app.kubernetes.io/instance: prometheus-pushgateway
    app.kubernetes.io/version: "v1.5.1"
    app.kubernetes.io/managed-by: Helm
  name: prometheus-pushgateway
  namespace: lma
