---
# Source: kiali-operator/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kiali-operator
  namespace: tks-msa
  labels:
    helm.sh/chart: kiali-operator-1.63.0
    app: kiali-operator
    app.kubernetes.io/name: kiali-operator
    app.kubernetes.io/instance: kiali-operator
    version: "v1.63.0"
    app.kubernetes.io/version: "v1.63.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: "kiali-operator"
...
