# Source: minio/templates/post-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: minio-post-job
  namespace: "lma"
  labels:
    app: minio-post-job
    chart: minio-5.0.4
    release: minio
    heritage: Helm
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
  template:
    metadata:
      labels:
        app: minio-job
        release: minio
    spec:
      restartPolicy: OnFailure
      
      volumes:
        - name: minio-configuration
          projected:
            sources:
              - configMap:
                  name: minio
              - secret:
                  name: minio
      containers:
        - name: minio-make-bucket
          image: "harbor.taco-cat.xyz/tks/mc:RELEASE.2023-01-11T03-14-16Z"
          imagePullPolicy: IfNotPresent
          command: [ "/bin/sh", "/config/initialize" ]
          env:
            - name: MINIO_ENDPOINT
              value: minio
            - name: MINIO_PORT
              value: "9000"
          volumeMounts:
            - name: minio-configuration
              mountPath: /config
          resources:
            requests:
              memory: 128Mi
        - name: minio-make-user
          image: "harbor.taco-cat.xyz/tks/mc:RELEASE.2023-01-11T03-14-16Z"
          imagePullPolicy: IfNotPresent
          command: [ "/bin/sh", "/config/add-user" ]
          env:
            - name: MINIO_ENDPOINT
              value: minio
            - name: MINIO_PORT
              value: "9000"
          volumeMounts:
            - name: minio-configuration
              mountPath: /config
          resources:
            requests:
              memory: 128Mi
        - name: minio-custom-command
          image: "harbor.taco-cat.xyz/tks/mc:RELEASE.2023-01-11T03-14-16Z"
          imagePullPolicy: IfNotPresent
          command: [ "/bin/sh", "/config/custom-command" ]
          env:
            - name: MINIO_ENDPOINT
              value: minio
            - name: MINIO_PORT
              value: "9000"
          volumeMounts:
            - name: minio-configuration
              mountPath: /config
          resources:
            requests:
              memory: 128Mi

