# Source: minio/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: minio
  namespace: "lma"
  labels:
    app: minio
    chart: minio-5.0.4
    release: minio
    heritage: Helm
type: Opaque
data:
  rootUser: "bFo3SVU0TEViUzR2RmxLWTNRcmg="
  rootPassword: "cnpFNXNudkM3YzBVeklYTEZMaVVrQWdPb3VObzlWMlh4U3NYVmp5OQ=="
