{
 "title": "[TKS] Kubernetes / View / Container",
 "description": "logging dashboard for container logs on TACO using https://grafana.com/grafana/dashboards/12611-logging-universal-dashboard/",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "cluster", "label": "Cluster", "query": "label_values(cluster)" },
   {
    "name": "kubernetes_namespace_name",
    "label": "Namespace",
    "query": "label_values({cluster=\"$cluster\"}, kubernetes_namespace_name)"
   },
   {
    "name": "kubernetes_pod_name",
    "label": "Pod",
    "query": "label_values({cluster=~\"$cluster\", kubernetes_namespace_name=\"$kubernetes_namespace_name\"}, kubernetes_pod_name)"
   },
   {
    "name": "kubernetes_container_name",
    "label": "Container",
    "query": "label_values({cluster=~\"$cluster\", kubernetes_namespace_name=\"$kubernetes_namespace_name\",kubernetes_pod_name=\"$kubernetes_pod_name\"}, kubernetes_container_name)"
   },
   { "name": "TopK", "query": "3,5,10,15,30,50,100" }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pods",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{taco_cluster=~\"$cluster\", namespace=~\"$kubernetes_namespace_name\", pod=~\"$kubernetes_pod_name\"})"
    }
   ]
  },
  {
   "title": "Abnormal Pods",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count((kube_pod_status_ready{condition=\"true\"} == 0) and ON(taco_cluster, namespace, pod) kube_pod_info{taco_cluster=~\"$cluster\", namespace=~\"$kubernetes_namespace_name\", pod=~\"$kubernetes_pod_name\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_info{taco_cluster=~\"$cluster\", namespace=~\"$kubernetes_namespace_name\", pod=~\"$kubernetes_pod_name\"})"
    }
   ]
  },
  {
   "title": "Abnormal Containers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_status_ready == 0 and ON(namespace, pod, container) kube_pod_container_info{taco_cluster=~\"$cluster\", namespace=~\"$kubernetes_namespace_name\", pod=~\"$kubernetes_pod_name\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Abnormal Containers",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "label_join((kube_pod_container_status_running == 0 or ON(namespace, pod, container) (increase(kube_pod_container_status_restarts_total[1h]) > 0)), \"key\", \"/\", \"namespace\", \"pod\") and ON(taco_cluster, namespace, pod, container) kube_pod_container_info{taco_cluster=~\"$cluster\", namespace=~\"$kubernetes_namespace_name\", pod=~\"$kubernetes_pod_name\"}"
    },
    {
     "expr": "label_join((increase(kube_pod_container_status_restarts_total[1h]) > 0), \"key\", \"/\", \"namespace\", \"pod\") and ON(taco_cluster, namespace, pod, container) kube_pod_container_info{taco_cluster=~\"$cluster\", namespace=~\"$kubernetes_namespace_name\", pod=~\"$kubernetes_pod_name\"}"
    }
   ]
  },
  {
   "title": "Trend for log collection",
   "type": "timeseries",
   "description": "Total  Count of log lines in the specified time range",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time(({cluster=~\"$cluster\", kubernetes_namespace_name=~\"$kubernetes_namespace_name\", kubernetes_container_name=~\"$kubernetes_container_name\", kubernetes_pod_name=~\"$kubernetes_pod_name\"})[$__interval]))"
    }
   ]
  },
  {
   "title": "Logs / Container",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 6 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(count_over_time(({cluster=~\"$cluster\", kubernetes_namespace_name=~\"$kubernetes_namespace_name\", kubernetes_pod_name=~\"$kubernetes_pod_name\"})[$__interval])) by (kubernetes_container_name)",
     "legendFormat": "{{kubernetes_container_name}}"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Live logs",
   "type": "logs",
   "description": "Live logs is a like 'tail -f' in a real time",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "{cluster=~\"$cluster\", kubernetes_namespace_name=~\"$kubernetes_namespace_name\", kubernetes_pod_name=~\"$kubernetes_pod_name\", kubernetes_container_name=~\"$kubernetes_container_name\"} "
    }
   ]
  },
  {
   "title": "Count of logs historical",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time(({cluster=~\"$cluster\", kubernetes_namespace_name=~\"$kubernetes_namespace_name\", kubernetes_pod_name=~\"$kubernetes_pod_name\"})[$__interval])) by (kubernetes_container_name)"
    }
   ]
  },
  {
   "title": "Resource (Relative Usage)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage (Relative to Total)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "topk($TopK, rate(container_cpu_usage_seconds_total{container!=\"\",taco_cluster=~\"$cluster\", namespace=~\"$kubernetes_namespace_name\", pod=~\"$kubernetes_pod_name\"}[5m]) / ON(taco_cluster, namespace, pod, container) (container_spec_cpu_quota/100000 > 0) )",
       "legendFormat": "{{ pod }} /{{ container }}"
      }
     ]
    },
    {
     "title": "Memory Usage (Relative to Total)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 17 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "topk($TopK, container_memory_working_set_bytes{container!=\"\",taco_cluster=~\"$cluster\", namespace=~\"$kubernetes_namespace_name\", pod=~\"$kubernetes_pod_name\"} / (container_spec_memory_limit_bytes > 0))",
       "legendFormat": "{{ pod }}/{{ container }}"
      }
     ]
    },
    {
     "title": "Volume Usage (Relative to Total)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 17 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "topk($TopK, kubelet_volume_stats_used_bytes/kubelet_volume_stats_capacity_bytes * ON(taco_cluster, namespace, persistentvolumeclaim) GROUP_RIGHT(volume, pod) kube_pod_spec_volumes_persistentvolumeclaims_info {taco_cluster=~\"$cluster\", namespace=~\"$kubernetes_namespace_name\", pod=~\"$kubernetes_pod_name\"})",
       "legendFormat": "{{ persistentvolumeclaim }} "
      }
     ]
    }
   ]
  },
  { "title": "Resource (Absolute Usage)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "CPU Usage (Absolute)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "core" }
   ],
   "targets": [
    {
     "expr": "topk($TopK, rate(container_cpu_usage_seconds_total{container!=\"\",taco_cluster=~\"$cluster\", namespace=~\"$kubernetes_namespace_name\", pod=~\"$kubernetes_pod_name\"}[5m]))",
     "legendFormat": "{{ pod }}/{{ container }}"
    }
   ]
  },
  {
   "title": "Memory Usage (Absolute)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 29 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk($TopK, container_memory_working_set_bytes{container!=\"\",taco_cluster=~\"$cluster\", namespace=~\"$kubernetes_namespace_name\", pod=~\"$kubernetes_pod_name\"} )",
     "legendFormat": "{{ pod }}/{{ container }}"
    }
   ]
  },
  {
   "title": "Volume Usage (Absolute)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 29 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk($TopK, kubelet_volume_stats_used_bytes * ON(taco_cluster, namespace, persistentvolumeclaim) GROUP_RIGHT(volume, pod) kube_pod_spec_volumes_persistentvolumeclaims_info{taco_cluster=~\"$cluster\", namespace=~\"$kubernetes_namespace_name\", pod=~\"$kubernetes_pod_name\"})",
     "legendFormat": "{{ persistentvolumeclaim }}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Packets Received",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "topk($TopK, rate(container_network_receive_packets_total{pod!=\"\", taco_cluster=~\"$cluster\", namespace=~\"$kubernetes_namespace_name\", pod=~\"$kubernetes_pod_name\"}[5m]))",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Packets Transmitted",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 40 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "topk($TopK, rate(container_network_transmit_packets_total{pod!=\"\", taco_cluster=~\"$cluster\", namespace=~\"$kubernetes_namespace_name\", pod=~\"$kubernetes_pod_name\"}[5m]))",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Bytes Received",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "topk($TopK, rate(container_network_receive_bytes_total{pod!=\"\", taco_cluster=~\"$cluster\", namespace=~\"$kubernetes_namespace_name\", pod=~\"$kubernetes_pod_name\"}[5m]))",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Bytes Transmitted",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 40 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "topk($TopK, rate(container_network_transmit_bytes_total{pod!=\"\", taco_cluster=~\"$cluster\", namespace=~\"$kubernetes_namespace_name\", pod=~\"$kubernetes_pod_name\"}[5m]))",
       "legendFormat": "{{ pod }}"
      }
     ]
    }
   ]
  }
 ]
}