# Source: lma-addons/templates/service-monitor/argo-rollouts.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: rollouts-controller
    app.kubernetes.io/instance: argo-rollouts
    app.kubernetes.io/name: argo-rollouts
  name: argo-rollouts
  namespace: lma
spec:
  jobLabel: argo-rollouts
  namespaceSelector:
    matchNames:
    - taco-system
  selector:
    matchLabels:
      app.kubernetes.io/component: rollouts-controller
      app.kubernetes.io/instance: argo-rollouts
      app.kubernetes.io/name: argo-rollouts
  endpoints:
  - port: metrics
    interval: 10s
