# Source: aws-cloud-controller-manager/templates/daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: aws-cloud-controller-manager
  labels:
    k8s-app:  aws-cloud-controller-manager
    helm.sh/chart: "aws-cloud-controller-manager-0.0.8"
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app:  aws-cloud-controller-manager
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      name: aws-cloud-controller-manager
      labels:
        k8s-app:  aws-cloud-controller-manager
    spec:
      tolerations: 
        - effect: NoSchedule
          key: node.cloudprovider.kubernetes.io/uninitialized
          value: "true"
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
      nodeSelector: 
        node-role.kubernetes.io/control-plane: ""
      dnsPolicy: Default
      priorityClassName: system-node-critical
      serviceAccountName: cloud-controller-manager
      securityContext:
        {}
      containers:
        - name: aws-cloud-controller-manager
          image: "harbor.taco-cat.xyz/tks/cloud-controller-manager:v1.27.1"
          args:
            - --v=2
            - --cloud-provider=aws
          resources:
            requests:
              cpu: 200m
          env:
            []
          securityContext:
            {}

