# Source: thanos/templates/query-frontend/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: thanos-query-frontend-configmap
  namespace: "lma"
  labels:
    app.kubernetes.io/name: thanos
    helm.sh/chart: thanos-12.3.2-skt
    app.kubernetes.io/instance: thanos
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: query-frontend
data:
  config.yml: |-
    type: IN-MEMORY
    config:
      max_size: 512MB
      max_size_items: 100
      validity: 100s
