# Source: prometheus-pushgateway/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    helm.sh/chart: prometheus-pushgateway-2.1.1
    app.kubernetes.io/name: prometheus-pushgateway
    app.kubernetes.io/instance: prometheus-pushgateway
    app.kubernetes.io/version: "v1.5.1"
    app.kubernetes.io/managed-by: Helm
  name: prometheus-pushgateway
  namespace: lma
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-pushgateway
      app.kubernetes.io/instance: prometheus-pushgateway
  template:
    metadata:
      labels:
        helm.sh/chart: prometheus-pushgateway-2.1.1
        app.kubernetes.io/name: prometheus-pushgateway
        app.kubernetes.io/instance: prometheus-pushgateway
        app.kubernetes.io/version: "v1.5.1"
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: prometheus-pushgateway
      containers:
        - name: pushgateway
          image: "harbor-cicd.taco-cat.xyz/tks/pushgateway:v1.3.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: metrics
              containerPort: 9091
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /-/ready
              port: 9091
            initialDelaySeconds: 10
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /-/ready
              port: 9091
            initialDelaySeconds: 10
            timeoutSeconds: 10
          volumeMounts:
            - name: storage-volume
              mountPath: "/data"
              subPath: ""
      nodeSelector:
        taco-lma: enabled
      securityContext:
        fsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
      volumes:
        - name: storage-volume
          emptyDir: {}

