---
# Source: thanos-config/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: taco-objstore-secret
  namespace: lma
stringData:
  objstore.yml: |-
    type: s3
    config:  
      access_key: taco
      aws_sdk_auth: true
      bucket: tks-thanos
      endpoint: minio.lma.svc:9000
      insecure: true
      secret_key: password

