# Source: fluentbit-resource/templates/fluentbit/filters.yaml
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterFilter
metadata:
  name: add-critical
  namespace: lma
  labels:
    fluentbit.fluent.io/enabled: "true"
    app.kubernetes.io/version: v0.0.1
spec:
  match: "m_critical.*"
  filters:
  - modify:
      rules:
      - add:
          level: critical
