# Source: lma-addons/templates/grafana-dashboard/configmap-datasources.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  namespace: lma
  labels:
    grafana_datasource: "1"
    app: grafana
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://lma-prometheus:9090
      access: proxy
      isDefault: true
    - name: Loki
      type: loki
      url: http://loki-loki-distributed-gateway:80
      access: proxy
