---
# Source: s3-chart/templates/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: s3-chart
    app.kubernetes.io/instance: s3-chart
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: "v1.0.3"
    k8s-app: s3-chart
    helm.sh/chart: s3-chart-v1.0.3
  name: ack-s3-controller
  namespace: taco-system
  annotations:
