# Source: kube-prometheus-stack/templates/alertmanager/alertmanager.yaml
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: lma-alertmanager
  namespace: lma
  labels:
    app: kube-prometheus-stack-alertmanager
    
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/version: "48.3.1"
    app.kubernetes.io/part-of: kube-prometheus-stack
    chart: kube-prometheus-stack-48.3.1
    release: "prometheus"
    heritage: "Helm"
spec:
  image: "harbor.taco-cat.xyz/tks/alertmanager:v0.25.0"
  version: v0.25.0
  replicas: 1
  listenLocal: false
  serviceAccountName: lma-alertmanager
  externalUrl: http://lma-alertmanager.lma:9093
  nodeSelector:
    taco-lma: enabled
  paused: false
  logFormat: "logfmt"
  logLevel:  "info"
  retention: "2h"
  alertmanagerConfigSelector:
    matchLabels:
      alertmanagerConfig: example

  alertmanagerConfigNamespaceSelector: {}
  routePrefix: "/"
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
  portName: http-web
