# Source: istiod/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: istiod-gateway-controller-tks-msa
  labels:
    app: istiod
    release: istiod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: istiod-gateway-controller-tks-msa
subjects:
- kind: ServiceAccount
  name: istiod
  namespace: tks-msa
