# Source: servicemesh-jaeger-resource/templates/job-create-es-user.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: create-es-user
  namespace: istio-system
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "20"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      name: create-es-user-template
    spec:
      containers:
      - name: esuser
        image: "docker.io/nginxinc/nginx-unprivileged:1.19-alpine"
        imagePullPolicy: "IfNotPresent"
        env:
        - name: ES_URL
          value: https://eck-elasticsearch-es-http.lma.svc.cluster.local:9200
        - name: ELASTIC_PW
          valueFrom:
            secretKeyRef:
              name: eck-elasticsearch-es-elastic-user
              key: elastic
        command:
        - timeout
        - 5m
        - /tmp/create_user.sh
        - taco-jaeger
        - password
        volumeMounts:
        - name: create-es-user-cm
          mountPath: /tmp/create_user.sh
          subPath: create_user.sh
          readOnly: true
      volumes:
      - name: create-es-user-cm
        configMap:
          name: create-es-user-cm
          defaultMode: 0777
      restartPolicy: OnFailure

