# Source: servicemesh-jaeger-resource/templates/create-cassandra-user-cm.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
  namespace: tks-msa
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "10"
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - secrets
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
