# Source: minio/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: minio
  namespace: "lma"
  labels:
    app: minio
    chart: minio-5.0.4
    release: minio
    heritage: Helm
type: Opaque
data:
  rootUser: "MWJFdU5CTnBHNjFZNnJoOUtLbEU="
  rootPassword: "dzRod2x2aHdEZmQzV0o1QW1Lb1ptanloQXpjS2tBZmVXbUM5emlRbQ=="
