# Source: tks-apis/templates/tks-api/sa-token.yaml
apiVersion: v1
kind: Secret
metadata:
  name: tks-api-token
  namespace: tks
  annotations:
    kubernetes.io/service-account.name: tks-api
type: kubernetes.io/service-account-token
